config/routes.rb
# encoding: utf-8

CartoDB::Application.routes.draw do
  root :to => 'admin/pages#public'

  get   '/datasets' => 'admin/pages#datasets'

  get   '/login' => 'sessions#new', :as => :login
  get   '/logout' => 'sessions#destroy', :as => :logout
  match '/sessions/create' => 'sessions#create', :as => :create_session
  match '/limits' => 'home#limits', :as => :limits
  match '/status' => 'home#app_status'

  get   '/test' => 'test#index', :as => :test

  scope :module => 'admin' do
    get '/dashboard/'                         => 'visualizations#index', :as => :dashboard

    resource :organization, only: [:show] do
      resources :users, only: [:edit, :update, :create, :destroy, :new], constraints: { id: /[0-z\.\-]+/ }
    end

    # Tables
    get '/dashboard/tables'                         => 'visualizations#index'
    get '/dashboard/tables/:page'                   => 'visualizations#index'
    get '/dashboard/tables/tag/:tag'                => 'visualizations#index'
    get '/dashboard/tables/tag/:tag/:page'          => 'visualizations#index'

    # Visualizations
    get '/dashboard/visualizations'                 => 'visualizations#index'
    get '/dashboard/visualizations/:page'           => 'visualizations#index'
    get '/dashboard/visualizations/tag/:tag'        => 'visualizations#index'
    get '/dashboard/visualizations/tag/:tag/:page'  => 'visualizations#index'

    # Search
    get '/dashboard/search/:q'                      => 'visualizations#index'
    get '/dashboard/search/:q/:page'                => 'visualizations#index'

    get '/dashboard/visualizations/search/:q'                      => 'visualizations#index'
    get '/dashboard/visualizations/search/:q/:page'                => 'visualizations#index'

    get '/dashboard/tables/search/:q'                      => 'visualizations#index'
    get '/dashboard/tables/search/:q/:page'                => 'visualizations#index'

    # Tags
    get '/dashboard/tag/:tag'                       => 'visualizations#index'

    # Private dashboard
    get '/dashboard'                => 'visualizations#index'
    get '/dashboard/common_data'    => 'pages#common_data'

    # Public dashboard
    # root goes to 'pages#public'
    get '/page/:page'               => 'pages#public'
    get '/tag/:tag'                 => 'pages#public', :as => :public_tag
    get '/tag/:tag/:page'           => 'pages#public'

    get '/datasets/page/:page'      => 'pages#datasets'
    get '/datasets/tag/:tag'        => 'pages#datasets', :as => :dataset_public_tag
    get '/datasets/tag/:tag/:page'  => 'pages#datasets'

    get '/tables/track_embed'       => 'visualizations#track_embed'
    get '/tables/embed_forbidden'   => 'visualizations#embed_forbidden'
    get '/tables/embed_protected'   => 'visualizations#embed_protected'
    get '/tables/:id'               => 'visualizations#show'
    get '/tables/:id/map'           => 'visualizations#show'
    get '/tables/:id/table'         => 'visualizations#show'
    get '/tables/:id/public'        => 'visualizations#public'
    get '/tables/:id/public/table'  => 'visualizations#public'
    get '/tables/:id/public/map'    => 'visualizations#public'
    get '/tables/:id/embed_map'     => 'visualizations#embed_map'

    get '/viz'                      => 'visualizations#index'
    get '/viz/track_embed'          => 'visualizations#track_embed'
    get '/viz/embed_forbidden'      => 'visualizations#embed_forbidden'
    get '/viz/:id'                  => 'visualizations#show'
    get '/viz/:id/map'              => 'visualizations#show'
    get '/viz/:id/table'            => 'visualizations#show'
    get '/viz/:id/public'           => 'visualizations#public'
    get '/viz/:id/embed_map'        => 'visualizations#embed_map'
    get '/viz/:id/public_map'       => 'visualizations#public_map'

    get '/viz/:id/protected_embed_map'  => 'visualizations#show_protected_embed_map'
    post '/viz/:id/protected_embed_map' => 'visualizations#show_protected_embed_map', :as => :protected_embed_map

    get '/viz/:id/protected_public_map'  => 'visualizations#show_protected_public_map'
    post '/viz/:id/protected_public_map' => 'visualizations#show_protected_public_map', :as => :protected_public_map

    match '/your_apps' => 'client_applications#api_key', :as => :api_key_credentials
    post  '/your_apps/api_key/regenerate' => 'client_applications#regenerate_api_key', :as => :regenerate_api_key
    delete  '/your_apps/oauth'   => 'client_applications#oauth',   :as => :oauth_credentials

  end


  namespace :superadmin do
    resources :users
    resources :synchronizations
  end

  scope :oauth, :path => :oauth do
    match '/authorize'      => 'oauth#authorize',     :as => :authorize
    match '/request_token'  => 'oauth#request_token', :as => :request_token
    match '/access_token'   => 'oauth#access_token',  :as => :access_token
    get   '/identity'       => 'sessions#show'
  end

  scope '/api' do
    namespace CartoDB::API::VERSION_1, :format => :json, :module => 'api/json' do
      get    '/column_types'                                    => 'meta#column_types'

      get '/get_authenticated_users'                         => 'users#get_authenticated_users'

      resources :tables, :only => [:create, :show, :update] do
        collection do
          get '/tags/:tag_name' => 'tables#index', :as => 'show_tag'
        end

        resources :records, :only => [:index, :create, :show, :update, :destroy]
        resources :columns, :only => [:index, :create, :show, :update, :destroy]
      end

      # imports
      resources :uploads, :only                           => :create
      resources :imports, :only                           => [:create, :show, :index]
      get     '/imports/service/:id/token_valid'          => 'imports#service_token_valid?'
      get     '/imports/service/:id/list_files'           => 'imports#list_files_for_service'
      get     '/imports/service/:id/auth_url'             => 'imports#get_service_auth_url'
      get     '/imports/service/:id/validate_code/:code'  => 'imports#validate_service_oauth_code'
      delete  '/imports/service/:id/invalidate_token'     => 'imports#invalidate_service_token'
      # Must be GET verb
      get     '/imports/service/:id/oauth_callback/'  => 'imports#service_oauth_callback'

      # Dashboard
      resources :users, :only                       => [:show] do
        resources :layers, :only                    => [:create, :index, :update, :destroy]
        resources :assets, :only                    => [:create, :index, :destroy]
      end

      # Maps
      resources :maps, :only                        => [:show, :create, :update, :destroy] do
        resources :layers, :only                    => [:show, :index, :create, :update, :destroy]
      end

      # Geocoder
      resources :geocodings, :only                  => [:create, :show, :index, :update] do
        get 'country_data_for/:country_code', to: 'geocodings#country_data_for', on: :collection, as: 'country_data'
        get 'estimation_for/:table_name',     to: 'geocodings#estimation_for',   on: :collection, as: 'estimation_for'
        get 'get_countries',                  to: 'geocodings#get_countries',    on: :collection, as: 'get_countries'
      end

      get     'viz/tags' => 'tags#index', :as => 'list_tags'
      get     'viz'                                 => 'visualizations#index'
      post    'viz'                                 => 'visualizations#create'
      get     'viz/:id/stats'                       => 'visualizations#stats'
      get     'viz/:id'                             => 'visualizations#show'
      put     'viz/:id'                             => 'visualizations#update'
      delete  'viz/:id'                             => 'visualizations#destroy'
      get     'viz/:id/viz'                         => 'visualizations#vizjson1', as: :vizjson
      get     'viz/:visualization_id/overlays'      => 'overlays#index'
      post    'viz/:visualization_id/overlays'      => 'overlays#create'
      get     'viz/:visualization_id/overlays/:id'  => 'overlays#show'
      put     'viz/:visualization_id/overlays/:id'  => 'overlays#update'
      delete  'viz/:visualization_id/overlays/:id'  => 'overlays#destroy'

      # Tags
      resources :tags, :only                                    => [:index]
      # Synchronizations
      get     'synchronizations'              => 'synchronizations#index'
      post    'synchronizations'              => 'synchronizations#create'
      get     'synchronizations/:id'          => 'synchronizations#show'
      put     'synchronizations/:id'          => 'synchronizations#update'
      delete  'synchronizations/:id'          => 'synchronizations#destroy'
      get     'synchronizations/:id/sync_now' => 'synchronizations#syncing?'
      put     'synchronizations/:id/sync_now' => 'synchronizations#sync_now'
    end

    get '/v2/viz/:id/viz'    => 'api/json/visualizations#vizjson2', as: :vizjson
    get '/v2/wms'            => 'api/json/wms#proxy'
    
  end
end

app/models/organization.rb
class Organization < Sequel::Model
  one_to_many :users
  plugin :validation_helpers

  def validate
    super
    validates_presence [:name, :quota_in_bytes]
    validates_unique   :name
    validates_format   /^[a-z0-9\-]+$/, :name, message: "must only contain lowercase letters, numbers & hyphens"
  end # validate

  def db_size_in_bytes
    users.map(&:db_size_in_bytes).sum.to_i
  end

  def assigned_quota
    users_dataset.sum(:quota_in_bytes).to_i
  end

  def unassigned_quota
    quota_in_bytes - assigned_quota
  end
end

app/controllers/admin/organizations_controller.rb
# coding: utf-8
class Admin::OrganizationsController < ApplicationController
  ssl_required :oauth, :api_key, :regenerate_api_key
  before_filter :login_required

  def show
    @organization = current_user.organization
    raise RecordNotFound unless @organization.present? && current_user.organization_owner
    @users = current_user.organization.users
  end
end

app/views/admin/organizations/_aside.html.erb
<div class="head">
  <h3>Your quota</h3>
</div>
<div class="content">
  <ul>
    <li>
      <div class="seats margin5">
        <div class="progress-bar">
          <span class="bar-2 used"></span>
        </div>
        <p class="margin10"><strong><%= "#{current_user.organization.users.count} of #{current_user.organization.seats}" %></strong> users in your account.</p>
      </div>
      <div class="space margin30">
        <div class="progress-bar">
          <span class="bar-2 used"></span>
          <span class="bar-1 available"></span>
          <span class="bar-0 unassigned" style="width:100%"></span>
        </div>
        <p class="margin10">
          <strong><%= number_to_human_size current_user.organization.db_size_in_bytes %> of <%= number_to_human_size current_user.organization.quota_in_bytes %></strong>
        used in your account.
        </p>
        <p class="margin5">
        <strong><%= number_to_human_size(current_user.organization.unassigned_quota) %></strong>
      unassigned.</p>
      </div>
    </li>
    <li>
      <%= link_to "Upgrade your quota", upgrade_url, :class => "button green" %>
    </li>
  </ul>
</div>

app/views/admin/organizations/_settings_account.html.erb
<% active = ['admin/organizations', 'admin/users'].include?(params[:controller]) -%>
<% if false && current_user.organization.present? && current_user.organization_owner %>
  <nav class="account-settings">
    <div class="inner">
      <a href="<%= organization_url %>" class="<%= 'selected' if active %>">
        <span class="icon organization"></span>
        <span class="info">
          <p class="strong">Manage your seats</p>
          <p><%= current_user.organization.users.count %> of <%= current_user.organization.seats %> in use</p>  
        </span>
      </a>
      <a href="<%= account_url %>">
        <span class="icon settings"></span>
        <span class="info">
          <p class="strong">Account settings</p>
          <p>Invoicing, access,...</p>
        </span>
      </a>
      <a class="disabled">
        <span class="icon stats"></span>
        <span class="info">
          <p class="strong">Public page</p>
          <p>Share your data</p>
        </span>
      </a>
    </div>
  </nav>
<% end %>

app/views/admin/organizations/show.html.erb
<% content_for(:page_title) do %>
  Your organization |
<% end %>
<%= content_for(:js) do %>
  <%= javascript_include_tag 'cdb.js', 'application.js', 'models.js', 'organization.js', 'templates.js' %>
  <script type="text/javascript">
    var username = "<%= current_user.username %>"
      , type = "oauth"
      , config = <%=raw frontend_config.html_safe %>
      , organization_quota = {
          seats: <%= current_user.organization.seats %>,
          quota_in_bytes: <%= current_user.organization.quota_in_bytes %>
        }
      , organization_users = <%= raw @users.map { |u| {
          id: u.id,
          username: u.username,
          quota_in_bytes: u.quota_in_bytes,
          remaining_quota: u.remaining_quota,
          organization_owner: u.organization_owner
        }}.to_json -%>
      , user_data = <%= raw current_user.data.to_json.html_safe %>;
  </script>
<% end %>
<%= content_for(:css) do %>
  <%= stylesheet_link_tag 'common.css', 'organization.css', :media => 'all' %>
<% end %>

<%= content_for(:account_settings) do %>
  <%= render partial: "settings_account" %>
<% end %>

<article>
  <div class="inner">
    <section class="block">
      <div class="head">
        <h2><%= current_user.organization.name.humanize %>'s users</h2>
      </div>
      <ul><%= render :partial => 'shared/flash_message' %></ul>
      <div class="list-head">
        <ul>
          <li><label>username</label></li>
          <li><label>quota</label></li>
        </ul>
      </div>
      <div class="content users_list">
        <ul>
          <% @users.each do |user| -%>
          <li>
            <div class="info">
              <%= link_to user.username, edit_organization_user_path(user.username) %>
              <% if user.organization_owner %>
                <span class="status owner">OWNER</span>
              <% end %>
            </div>
            <div class="storage">
              <div class="progress-bar"></div>
            </div>
          </li>
          <% end -%>
        </ul>
      </div>
      <div class="foot">
        <% if current_user.organization.seats > @users.count %>
          <%= link_to "Add new user", new_organization_user_path, :class => 'right button grey' %>
        <% else %>
          <%= link_to "Upgrade your quota", upgrade_url, :class => "button green right" %>
        <% end %>
      </div>
    </section>
  </div>
</article>