config/routes.rb
# encoding: utf-8

CartoDB::Application.routes.draw do
  root :to => 'admin/pages#public'

  get   '/datasets' => 'admin/pages#datasets'

  get   '/login' => 'sessions#new', :as => :login
  get   '/logout' => 'sessions#destroy', :as => :logout
  match '/sessions/create' => 'sessions#create', :as => :create_session
  match '/limits' => 'home#limits', :as => :limits
  match '/status' => 'home#app_status'

  get   '/test' => 'test#index', :as => :test

  scope :module => 'admin' do
    get '/dashboard/'                         => 'visualizations#index', :as => :dashboard

    resource :organization, only: [:show] do
      resources :users, only: [:edit, :update, :create, :destroy, :new], constraints: { id: /[0-z\.\-]+/ }
    end

    # Tables
    get '/dashboard/tables'                         => 'visualizations#index'
    get '/dashboard/tables/:page'                   => 'visualizations#index'
    get '/dashboard/tables/tag/:tag'                => 'visualizations#index'
    get '/dashboard/tables/tag/:tag/:page'          => 'visualizations#index'

    # Visualizations
    get '/dashboard/visualizations'                 => 'visualizations#index'
    get '/dashboard/visualizations/:page'           => 'visualizations#index'
    get '/dashboard/visualizations/tag/:tag'        => 'visualizations#index'
    get '/dashboard/visualizations/tag/:tag/:page'  => 'visualizations#index'

    # Search
    get '/dashboard/search/:q'                      => 'visualizations#index'
    get '/dashboard/search/:q/:page'                => 'visualizations#index'

    get '/dashboard/visualizations/search/:q'                      => 'visualizations#index'
    get '/dashboard/visualizations/search/:q/:page'                => 'visualizations#index'

    get '/dashboard/tables/search/:q'                      => 'visualizations#index'
    get '/dashboard/tables/search/:q/:page'                => 'visualizations#index'

    # Tags
    get '/dashboard/tag/:tag'                       => 'visualizations#index'

    # Private dashboard
    get '/dashboard'                => 'visualizations#index'
    get '/dashboard/common_data'    => 'pages#common_data'

    # Public dashboard
    # root goes to 'pages#public'
    get '/page/:page'               => 'pages#public'
    get '/tag/:tag'                 => 'pages#public', :as => :public_tag
    get '/tag/:tag/:page'           => 'pages#public'

    get '/datasets/page/:page'      => 'pages#datasets'
    get '/datasets/tag/:tag'        => 'pages#datasets', :as => :dataset_public_tag
    get '/datasets/tag/:tag/:page'  => 'pages#datasets'

    get '/tables/track_embed'       => 'visualizations#track_embed'
    get '/tables/embed_forbidden'   => 'visualizations#embed_forbidden'
    get '/tables/embed_protected'   => 'visualizations#embed_protected'
    get '/tables/:id'               => 'visualizations#show'
    get '/tables/:id/map'           => 'visualizations#show'
    get '/tables/:id/table'         => 'visualizations#show'
    get '/tables/:id/public'        => 'visualizations#public'
    get '/tables/:id/public/table'  => 'visualizations#public'
    get '/tables/:id/public/map'    => 'visualizations#public'
    get '/tables/:id/embed_map'     => 'visualizations#embed_map'

    get '/viz'                      => 'visualizations#index'
    get '/viz/track_embed'          => 'visualizations#track_embed'
    get '/viz/embed_forbidden'      => 'visualizations#embed_forbidden'
    get '/viz/:id'                  => 'visualizations#show'
    get '/viz/:id/map'              => 'visualizations#show'
    get '/viz/:id/table'            => 'visualizations#show'
    get '/viz/:id/public'           => 'visualizations#public'
    get '/viz/:id/embed_map'        => 'visualizations#embed_map'
    get '/viz/:id/public_map'       => 'visualizations#public_map'

    get '/viz/:id/protected_embed_map'  => 'visualizations#show_protected_embed_map'
    post '/viz/:id/protected_embed_map' => 'visualizations#show_protected_embed_map', :as => :protected_embed_map

    get '/viz/:id/protected_public_map'  => 'visualizations#show_protected_public_map'
    post '/viz/:id/protected_public_map' => 'visualizations#show_protected_public_map', :as => :protected_public_map

    match '/your_apps' => 'client_applications#api_key', :as => :api_key_credentials
    post  '/your_apps/api_key/regenerate' => 'client_applications#regenerate_api_key', :as => :regenerate_api_key
    delete  '/your_apps/oauth'   => 'client_applications#oauth',   :as => :oauth_credentials

  end


  namespace :superadmin do
    resources :users
    resources :synchronizations
  end

  scope :oauth, :path => :oauth do
    match '/authorize'      => 'oauth#authorize',     :as => :authorize
    match '/request_token'  => 'oauth#request_token', :as => :request_token
    match '/access_token'   => 'oauth#access_token',  :as => :access_token
    get   '/identity'       => 'sessions#show'
  end

  scope '/api' do
    namespace CartoDB::API::VERSION_1, :format => :json, :module => 'api/json' do
      get    '/column_types'                                    => 'meta#column_types'

      get '/get_authenticated_users'                         => 'users#get_authenticated_users'

      resources :tables, :only => [:create, :show, :update] do
        collection do
          get '/tags/:tag_name' => 'tables#index', :as => 'show_tag'
        end

        resources :records, :only => [:index, :create, :show, :update, :destroy]
        resources :columns, :only => [:index, :create, :show, :update, :destroy]
      end

      # imports
      resources :uploads, :only                           => :create
      resources :imports, :only                           => [:create, :show, :index]
      get     '/imports/service/:id/token_valid'          => 'imports#service_token_valid?'
      get     '/imports/service/:id/list_files'           => 'imports#list_files_for_service'
      get     '/imports/service/:id/auth_url'             => 'imports#get_service_auth_url'
      get     '/imports/service/:id/validate_code/:code'  => 'imports#validate_service_oauth_code'
      delete  '/imports/service/:id/invalidate_token'     => 'imports#invalidate_service_token'
      # Must be GET verb
      get     '/imports/service/:id/oauth_callback/'  => 'imports#service_oauth_callback'

      # Dashboard
      resources :users, :only                       => [:show] do
        resources :layers, :only                    => [:create, :index, :update, :destroy]
        resources :assets, :only                    => [:create, :index, :destroy]
      end

      # Maps
      resources :maps, :only                        => [:show, :create, :update, :destroy] do
        resources :layers, :only                    => [:show, :index, :create, :update, :destroy]
      end

      # Geocoder
      resources :geocodings, :only                  => [:create, :show, :index, :update] do
        get 'country_data_for/:country_code', to: 'geocodings#country_data_for', on: :collection, as: 'country_data'
        get 'estimation_for/:table_name',     to: 'geocodings#estimation_for',   on: :collection, as: 'estimation_for'
        get 'get_countries',                  to: 'geocodings#get_countries',    on: :collection, as: 'get_countries'
      end

      get     'viz/tags' => 'tags#index', :as => 'list_tags'
      get     'viz'                                 => 'visualizations#index'
      post    'viz'                                 => 'visualizations#create'
      get     'viz/:id/stats'                       => 'visualizations#stats'
      get     'viz/:id'                             => 'visualizations#show'
      put     'viz/:id'                             => 'visualizations#update'
      delete  'viz/:id'                             => 'visualizations#destroy'
      get     'viz/:id/viz'                         => 'visualizations#vizjson1', as: :vizjson
      get     'viz/:visualization_id/overlays'      => 'overlays#index'
      post    'viz/:visualization_id/overlays'      => 'overlays#create'
      get     'viz/:visualization_id/overlays/:id'  => 'overlays#show'
      put     'viz/:visualization_id/overlays/:id'  => 'overlays#update'
      delete  'viz/:visualization_id/overlays/:id'  => 'overlays#destroy'

      # Tags
      resources :tags, :only                                    => [:index]
      # Synchronizations
      get     'synchronizations'              => 'synchronizations#index'
      post    'synchronizations'              => 'synchronizations#create'
      get     'synchronizations/:id'          => 'synchronizations#show'
      put     'synchronizations/:id'          => 'synchronizations#update'
      delete  'synchronizations/:id'          => 'synchronizations#destroy'
      get     'synchronizations/:id/sync_now' => 'synchronizations#syncing?'
      put     'synchronizations/:id/sync_now' => 'synchronizations#sync_now'
    end

    get '/v2/viz/:id/viz'    => 'api/json/visualizations#vizjson2', as: :vizjson
    get '/v2/wms'            => 'api/json/wms#proxy'
    
  end
end

app/models/user/oauths.rb
module CartoDB
  # This class encapsulates access to synchronization_oauths from the outside
  class OAuths

    # Class constructor
    # @param owner_user User
    def initialize(owner_user)
      @owner = owner_user
    end #initialize

    def all
      @owner.synchronization_oauths
    end #all

    # @param service string
    # @return SynchronizationOauth
    def select(service)
      SynchronizationOauth.where(service: service, user_id: @owner.id).first
    end #select

    def add(service, token)
      new_oauth = SynchronizationOauth.create(
          user_id:  @owner.id,
          service:  service,
          token:    token
      )
      @owner.add_synchronization_oauth(new_oauth)
      self
    end

    def remove(service)
      oauth = SynchronizationOauth.where(service: service, user_id: @owner.id).first
      oauth.delete unless oauth.nil?
      @owner.reload
      self
    end

  end #OAuths
end #CartoDB

app/controllers/admin/users_controller.rb
# coding: utf-8
class Admin::UsersController < ApplicationController
  ssl_required :oauth, :api_key, :regenerate_api_key

  before_filter :login_required, :check_permissions
  before_filter :get_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
    @user.quota_in_bytes = (current_user.organization.unassigned_quota < 100.megabytes ? current_user.organization.unassigned_quota : 100.megabytes)
  end

  def edit; end

  def create
    @user = User.new
    @user.set_fields(params[:user], [:username, :email, :password, :quota_in_bytes, :password_confirmation])
    @user.organization = current_user.organization
    @user.username = "#{@user.username}.#{current_user.organization.name}" unless @user.username =~ /\.#{current_user.organization.name}/
    copy_account_features(current_user, @user)
    @user.save(raise_on_failure: true)
    redirect_to organization_path, flash: { success: "New user created successfully" }
  rescue Sequel::ValidationFailed => e
    render action: :new
  end

  def update
    attributes = params[:user]
    @user.set_fields(attributes, [:email])
    @user.set_fields(attributes, [:quota_in_bytes]) if current_user.organization_owner
    @user.password = attributes[:password] if attributes[:password].present?
    @user.password_confirmation = attributes[:password_confirmation] if attributes[:password_confirmation].present?

    @user.save(raise_on_failure: true)
    redirect_to edit_organization_user_path(@user.username), flash: { success: "Updated successfully" }
  rescue Sequel::ValidationFailed => e
    render action: :edit
  end

  def destroy
    @user.destroy
    head :no_content
  end

  private

  def check_permissions
    raise RecordNotFound unless current_user.organization.present?
    raise RecordNotFound unless current_user.organization_owner || ['edit', 'update'].include?(params[:action])
  end

  def get_user
    @user = current_user.organization.users_dataset.where(username: params[:id]).first
    raise RecordNotFound unless @user
    raise RecordNotFound unless current_user.organization_owner || current_user == @user
  end

  def copy_account_features(from, to)
    to.set_fields(from, [
      :private_tables_enabled, :sync_tables_enabled, :max_layers, :user_timeout,
      :database_timeout, :geocoding_quota, :map_view_quota, :table_quota, :database_host,
      :period_end_date, :map_view_block_price, :geocoding_block_price, :account_type
    ])
    to.invite_token = User.make_token
  end
end

app/controllers/api/json/users_controller.rb
class Api::Json::UsersController < Api::ApplicationController
  skip_before_filter :api_authorization_required, only: [:get_authenticated_users]
  ssl_required :get_authenticated_users

  if Rails.env.production? || Rails.env.staging?
    ssl_required :show
  end

  def show
    user = current_user
    render json: user.data
  end

  def get_authenticated_users
    render json: request.session.select {|k,v| k.start_with?("warden.user")}.values
  end

end

app/controllers/superadmin/users_controller.rb
class Superadmin::UsersController < Superadmin::SuperadminController
  respond_to :json

  ssl_required :show, :create, :update, :destroy, :index if Rails.env.production? || Rails.env.staging?
  before_filter :get_user, only: [:update, :destroy, :show]

  layout 'application'

  ALLOWED_ATTRIBUTES = [
    :username, :email, :admin, :quota_in_bytes, :table_quota, :account_type,
    :private_tables_enabled, :sync_tables_enabled, :map_view_quota, :map_view_block_price,
    :geocoding_quota, :geocoding_block_price, :period_end_date, :max_layers, :user_timeout,
    :database_timeout, :database_host, :upgraded_at, :notification, :organization_owner,
    :disqus_shortname
  ]

  def show
    respond_with(@user.data(:extended => true))
  end

  def index
    @users = (params[:overquota].present? ? User.overquota(0.20) : User.all)
    respond_with(:superadmin, @users.map(&:data))
  end

  def create
    @user = User.new
    attributes = params[:user]
    @user.set_only(attributes, ALLOWED_ATTRIBUTES)
    @user.enabled = true
    set_password_if_present(attributes)

    @user.save
    respond_with(:superadmin, @user)
  end

  def update
    attributes = params[:user]
    @user.set_only(attributes, ALLOWED_ATTRIBUTES)
    set_password_if_present(attributes)
    set_organization_if_present(attributes)

    @user.save
    respond_with(:superadmin, @user)
  end

  def destroy
    @user.destroy
    respond_with(:superadmin, @user)
  end

  private

  def get_user
    @user = User[params[:id]]
    raise RecordNotFound unless @user
  end # get_user

  def set_password_if_present(attributes)
    @user.password         = attributes[:password] if attributes[:password].present?
    @user.password_confirmation = attributes[:password] if attributes[:password].present?
    @user.crypted_password = attributes[:crypted_password] if attributes[:crypted_password].present?
    @user.salt             = attributes[:salt] if attributes[:salt].present?
  end # set_password_if_present

  def set_organization_if_present(attributes)
    return if attributes[:organization_attributes].blank?
    organization = (@user.organization.blank? ? Organization.new : @user.organization)
    organization.set_only(attributes[:organization_attributes], [:name, :seats, :quota_in_bytes])
    organization.save
    @user.organization = organization
  end
end # Superadmin::UsersController

app/views/admin/users/_form.html.erb
  <script type="text/javascript">
    var organization_users = <%= raw current_user.organization.users.map { |u| {
      id: u.id,
      username: u.username, 
      quota_in_bytes: u.quota_in_bytes, 
      remaining_quota: u.remaining_quota,
      organization_owner: u.organization_owner
    }}.to_json -%>;
    <% if !@user.new? %>
    var organization_user_data = <%= raw @user.data.to_json.html_safe -%>;
    <% end %>
  </script>


<%= form_for @user, url: (@user.new? ? organization_users_path(@organization) : organization_user_path(@user.username)) do |form| %>

  <%= form.hidden_field :private_tables_enabled %>

  <div class="head">
    <h2>
      <% if @user.new? -%>
        Create new user
      <% else %>
        <%= "#{@user.username} details" %>
      <% end %>
    </h2>
  </div>

  <ul><%= render partial: 'shared/flash_message' %></ul>
  
  <% if !@user.new? && current_user.organization_owner -%>
  <div class="content user-details">
    <ul>
      <li><%= @user.tables.count %> tables created</li>
      <li><%= @user.visualization_count %> visualizations created</li>
      <li><%= @user.get_geocoding_calls %> georeferenced rows</li>

      <%#
        It needs to know the limits:
          · quota used < 75% -> ok
          · quota used => 75% && quota used < 95% -> danger
          · quota used => 95% -> boom
      -%>
      <% used_percentage = @user.db_size_in_bytes / @user.quota_in_bytes.to_f -%>
      <% user_type = case used_percentage
      when 0..0.7
        'ok'
      when 0.7..0.9
        'danger'
      else
        'boom'
      end -%> 

      <li><strong class="<%= user_type %>"><%= number_to_percentage used_percentage, precision: 2 %></strong> of user quota used</li>
      <li><%= @user.get_api_calls(from: @user.last_billing_cycle, to: Date.today).sum %> map views this month</li>
      <li>Last access: <%= "#{distance_of_time_in_words_to_now(@user.get_last_active_time)} ago" rescue "--" %></li>
    </ul>
  </div>
  <% end %>

  <div class="content">
    <div class="org-user-form">

      <div class="left-column">
        <div class="row">
          <div class="field field-2">
            <%= form.label :username %>
            <%= form.text_field :username, :class => @user.errors[:username].present? ? 'error' : nil, :disabled => !@user.new? %>
            <%= form_error_for :username, @user.errors %>
          </div>
        </div>

        <div class="row">
          <div class="field field-2">
            <%= form.label :email %>
            <%= form.text_field :email, :class => @user.errors[:email].present? ? 'error' : nil %>
            <%= form_error_for :email, @user.errors %>
          </div>
        </div>

        <div class="row">
          <div class="field field-2">
            <%= label_tag 'user[password]', 'New password' %>
            <%= password_field_tag 'user[password]', nil, :class => @user.errors[:password].present? ? 'error' : nil %>
            <%= form_error_for :password, @user.errors %>
          </div>
          <div class="field field-2">
            <%= label_tag 'user[password_confirmation]', 'Confirm password' %>
            <%= password_field_tag 'user[password_confirmation]', nil, :class => @user.errors[:password].present? ? 'error' : nil %>
            <%= form_error_for :password_confirmation, @user.errors %>
          </div>
        </div>
        
        <% if current_user.organization_owner -%>
          <div class="row">
            <div class="field field-1">
              <label>
                <% if @user.new? -%>
                  New user will have
                <% else %>
                  <%= @user.username %> has
                <% end %>
                <strong><%= number_to_human_size(@user.quota_in_bytes) %> assigned</strong> -
                <a href="#/change-quota" class="change_quota">change</a>
              </label>
              <div class="progress-bar"></div>
              <%= form.hidden_field :quota_in_bytes, :class => @user.errors[:quota_in_bytes].present? ? 'error' : nil, :id => "user_quota" %>
              <%= form_error_for :quota_in_bytes, @user.errors %>
            </div>
          </div>

          <!-- USER EXTRAS -->
          <% if false %>
            <div class="extras margin20">
              <div class="row">
                <div class="field field-1">
                  <label class="bottom-border">EXTRAS</label>
                  <div class="extra margin15">
                    <div class="left">
                      <span class="light">Allow geocoding</span>
                    </div>
                    <div class="right">
                      <input type="checkbox" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>

        <% end -%>
      </div>

      <div class="right-column">
        <div class="row">
          <p>Subdomain cannot be changed</p>
        </div>
        <div class="row">
          <p>
            <% unless @user.new? -%>
              <% if current_user.organization_owner -%>
                This user
                <%= @user.new? ? "will enter" : "enters" %>
              <% else %>
                You enter
              <% end %>
              through <%= link_to "#{@user.username}#{Cartodb.config[:session_domain]}", "http://#{@user.username}#{Cartodb.config[:session_domain]}" %></p>
            <% end -%>
        </div>

        <% if current_user.organization_owner -%>
          <div class="row">
            <% if false %><p>Or <a href="#/generate-pass" class="pass-generator">generate</a> a random password for this user</p><% end %>
          </div>
          <div class="row">
            <p>Do you need more quota? <%= link_to 'Upgrade your account', upgrade_url %></p>
          </div>
        <% end %>
      </div>

    </div>
  </div>

  <div class="foot">
    <% if !@user.new? -%>
      <%= link_to("delete this user", organization_user_path(@user.username), :class => "left delete red margin15") if current_user.organization_owner %>
      <%= form.submit 'Save changes', :class => "right grey button new" %>
    <% else %>
      <%= form.submit 'Create user', :class => "right grey button new" %>
    <% end %>
  </div>

<% end %>

app/views/admin/users/edit.html.erb
<% content_for(:page_title) do %>
  Edit user information |
<% end %>
<%= content_for(:js) do %>
  <%= javascript_include_tag 'cdb.js', 'application.js', 'models.js', 'organization.js', 'templates.js' %>
  <script type="text/javascript">
    var username = "<%= current_user.username %>"
      , type = "oauth"
      , config = <%=raw frontend_config.html_safe %>
      , organization_quota = {
          seats: <%= current_user.organization.seats %>,
          quota_in_bytes: <%= current_user.organization.quota_in_bytes %>
        }
      , user_data = <%=raw current_user.data.to_json.html_safe %>;
  </script>
<% end %>
<%= content_for(:css) do %>
  <%= stylesheet_link_tag 'common.css', 'organization.css', :media => 'all' %>
<% end %>

<%= content_for(:account_settings) do %>
  <%= render partial: "admin/organizations/settings_account" %>
<% end %>

<article>
  <div class="inner">
    <section class="block">
      <% if current_user.organization_owner %>
        <%= link_to "back", organization_url, :class => "back" %>
      <% end %>
      <%= render partial: 'form' %>
    </section>
  </div>
</article>

app/views/admin/users/new.html.erb
<% content_for(:page_title) do %>
  Add a new user |
<% end %>
<%= content_for(:js) do %>
  <%= javascript_include_tag 'cdb.js', 'application.js', 'models.js', 'organization.js', 'templates.js' %>
  <script type="text/javascript">
    var username = "<%= current_user.username %>"
      , type = "oauth"
      , config = <%=raw frontend_config.html_safe %>
      , organization_quota = {
          seats: <%= current_user.organization.seats %>,
          quota_in_bytes: <%= current_user.organization.quota_in_bytes %>
        }
      , user_data = <%=raw current_user.data.to_json.html_safe %>;
  </script>
<% end %>
<%= content_for(:css) do %>
  <%= stylesheet_link_tag 'common.css', 'organization.css', :media => 'all' %>
<% end %>

<%= content_for(:account_settings) do %>
  <%= render partial: "admin/organizations/settings_account" %>
<% end %>

<article>

  <div class="inner">
    <section class="block">
      <%= link_to "back", organization_url, :class => "back" %>
      <%= render partial: 'form' %>
    </section>
  </div>
</article>