config/routes.rb
# encoding: utf-8

CartoDB::Application.routes.draw do
  root :to => 'admin/pages#public'

  get   '/datasets' => 'admin/pages#datasets'

  get   '/login' => 'sessions#new', :as => :login
  get   '/logout' => 'sessions#destroy', :as => :logout
  match '/sessions/create' => 'sessions#create', :as => :create_session
  match '/limits' => 'home#limits', :as => :limits
  match '/status' => 'home#app_status'

  get   '/test' => 'test#index', :as => :test

  scope :module => 'admin' do
    get '/dashboard/'                         => 'visualizations#index', :as => :dashboard

    resource :organization, only: [:show] do
      resources :users, only: [:edit, :update, :create, :destroy, :new], constraints: { id: /[0-z\.\-]+/ }
    end

    # Tables
    get '/dashboard/tables'                         => 'visualizations#index'
    get '/dashboard/tables/:page'                   => 'visualizations#index'
    get '/dashboard/tables/tag/:tag'                => 'visualizations#index'
    get '/dashboard/tables/tag/:tag/:page'          => 'visualizations#index'

    # Visualizations
    get '/dashboard/visualizations'                 => 'visualizations#index'
    get '/dashboard/visualizations/:page'           => 'visualizations#index'
    get '/dashboard/visualizations/tag/:tag'        => 'visualizations#index'
    get '/dashboard/visualizations/tag/:tag/:page'  => 'visualizations#index'

    # Search
    get '/dashboard/search/:q'                      => 'visualizations#index'
    get '/dashboard/search/:q/:page'                => 'visualizations#index'

    get '/dashboard/visualizations/search/:q'                      => 'visualizations#index'
    get '/dashboard/visualizations/search/:q/:page'                => 'visualizations#index'

    get '/dashboard/tables/search/:q'                      => 'visualizations#index'
    get '/dashboard/tables/search/:q/:page'                => 'visualizations#index'

    # Tags
    get '/dashboard/tag/:tag'                       => 'visualizations#index'

    # Private dashboard
    get '/dashboard'                => 'visualizations#index'
    get '/dashboard/common_data'    => 'pages#common_data'

    # Public dashboard
    # root goes to 'pages#public'
    get '/page/:page'               => 'pages#public'
    get '/tag/:tag'                 => 'pages#public', :as => :public_tag
    get '/tag/:tag/:page'           => 'pages#public'

    get '/datasets/page/:page'      => 'pages#datasets'
    get '/datasets/tag/:tag'        => 'pages#datasets', :as => :dataset_public_tag
    get '/datasets/tag/:tag/:page'  => 'pages#datasets'

    get '/tables/track_embed'       => 'visualizations#track_embed'
    get '/tables/embed_forbidden'   => 'visualizations#embed_forbidden'
    get '/tables/embed_protected'   => 'visualizations#embed_protected'
    get '/tables/:id'               => 'visualizations#show'
    get '/tables/:id/map'           => 'visualizations#show'
    get '/tables/:id/table'         => 'visualizations#show'
    get '/tables/:id/public'        => 'visualizations#public'
    get '/tables/:id/public/table'  => 'visualizations#public'
    get '/tables/:id/public/map'    => 'visualizations#public'
    get '/tables/:id/embed_map'     => 'visualizations#embed_map'

    get '/viz'                      => 'visualizations#index'
    get '/viz/track_embed'          => 'visualizations#track_embed'
    get '/viz/embed_forbidden'      => 'visualizations#embed_forbidden'
    get '/viz/:id'                  => 'visualizations#show'
    get '/viz/:id/map'              => 'visualizations#show'
    get '/viz/:id/table'            => 'visualizations#show'
    get '/viz/:id/public'           => 'visualizations#public'
    get '/viz/:id/embed_map'        => 'visualizations#embed_map'
    get '/viz/:id/public_map'       => 'visualizations#public_map'

    get '/viz/:id/protected_embed_map'  => 'visualizations#show_protected_embed_map'
    post '/viz/:id/protected_embed_map' => 'visualizations#show_protected_embed_map', :as => :protected_embed_map

    get '/viz/:id/protected_public_map'  => 'visualizations#show_protected_public_map'
    post '/viz/:id/protected_public_map' => 'visualizations#show_protected_public_map', :as => :protected_public_map

    match '/your_apps' => 'client_applications#api_key', :as => :api_key_credentials
    post  '/your_apps/api_key/regenerate' => 'client_applications#regenerate_api_key', :as => :regenerate_api_key
    delete  '/your_apps/oauth'   => 'client_applications#oauth',   :as => :oauth_credentials

  end


  namespace :superadmin do
    resources :users
    resources :synchronizations
  end

  scope :oauth, :path => :oauth do
    match '/authorize'      => 'oauth#authorize',     :as => :authorize
    match '/request_token'  => 'oauth#request_token', :as => :request_token
    match '/access_token'   => 'oauth#access_token',  :as => :access_token
    get   '/identity'       => 'sessions#show'
  end

  scope '/api' do
    namespace CartoDB::API::VERSION_1, :format => :json, :module => 'api/json' do
      get    '/column_types'                                    => 'meta#column_types'

      get '/get_authenticated_users'                         => 'users#get_authenticated_users'

      resources :tables, :only => [:create, :show, :update] do
        collection do
          get '/tags/:tag_name' => 'tables#index', :as => 'show_tag'
        end

        resources :records, :only => [:index, :create, :show, :update, :destroy]
        resources :columns, :only => [:index, :create, :show, :update, :destroy]
      end

      # imports
      resources :uploads, :only                           => :create
      resources :imports, :only                           => [:create, :show, :index]
      get     '/imports/service/:id/token_valid'          => 'imports#service_token_valid?'
      get     '/imports/service/:id/list_files'           => 'imports#list_files_for_service'
      get     '/imports/service/:id/auth_url'             => 'imports#get_service_auth_url'
      get     '/imports/service/:id/validate_code/:code'  => 'imports#validate_service_oauth_code'
      delete  '/imports/service/:id/invalidate_token'     => 'imports#invalidate_service_token'
      # Must be GET verb
      get     '/imports/service/:id/oauth_callback/'  => 'imports#service_oauth_callback'

      # Dashboard
      resources :users, :only                       => [:show] do
        resources :layers, :only                    => [:create, :index, :update, :destroy]
        resources :assets, :only                    => [:create, :index, :destroy]
      end

      # Maps
      resources :maps, :only                        => [:show, :create, :update, :destroy] do
        resources :layers, :only                    => [:show, :index, :create, :update, :destroy]
      end

      # Geocoder
      resources :geocodings, :only                  => [:create, :show, :index, :update] do
        get 'country_data_for/:country_code', to: 'geocodings#country_data_for', on: :collection, as: 'country_data'
        get 'estimation_for/:table_name',     to: 'geocodings#estimation_for',   on: :collection, as: 'estimation_for'
        get 'get_countries',                  to: 'geocodings#get_countries',    on: :collection, as: 'get_countries'
      end

      get     'viz/tags' => 'tags#index', :as => 'list_tags'
      get     'viz'                                 => 'visualizations#index'
      post    'viz'                                 => 'visualizations#create'
      get     'viz/:id/stats'                       => 'visualizations#stats'
      get     'viz/:id'                             => 'visualizations#show'
      put     'viz/:id'                             => 'visualizations#update'
      delete  'viz/:id'                             => 'visualizations#destroy'
      get     'viz/:id/viz'                         => 'visualizations#vizjson1', as: :vizjson
      get     'viz/:visualization_id/overlays'      => 'overlays#index'
      post    'viz/:visualization_id/overlays'      => 'overlays#create'
      get     'viz/:visualization_id/overlays/:id'  => 'overlays#show'
      put     'viz/:visualization_id/overlays/:id'  => 'overlays#update'
      delete  'viz/:visualization_id/overlays/:id'  => 'overlays#destroy'

      # Tags
      resources :tags, :only                                    => [:index]
      # Synchronizations
      get     'synchronizations'              => 'synchronizations#index'
      post    'synchronizations'              => 'synchronizations#create'
      get     'synchronizations/:id'          => 'synchronizations#show'
      put     'synchronizations/:id'          => 'synchronizations#update'
      delete  'synchronizations/:id'          => 'synchronizations#destroy'
      get     'synchronizations/:id/sync_now' => 'synchronizations#syncing?'
      put     'synchronizations/:id/sync_now' => 'synchronizations#sync_now'
    end

    get '/v2/viz/:id/viz'    => 'api/json/visualizations#vizjson2', as: :vizjson
    get '/v2/wms'            => 'api/json/wms#proxy'
    
  end
end

app/views/admin/shared/_footer.html.erb
<footer>
  <div class="inner">
    <nav class="left">
      <%= link_to "Feature tour", "http://cartodb.com/tour" %>
      <%= link_to "Getting started", "#{Cartodb.config[:developers_host]}/tutorials.html" %>
      <%= link_to "Documentation", Cartodb.config[:developers_host] %>
      <%= link_to "Support", "http://support.cartodb.com" %>
      <%= link_to "Contact", "mailto:contact@cartodb.com" %>
    </nav>
    <p class="right">CartoDB is a product of <%= link_to "Vizzuality", "http://vizzuality.com", :target => "blank" %></p>
  </div>
</footer>

app/views/admin/shared/_header.html.erb
<header>
  <div class="inner">
    <h1 class="left"><%= link_to "CartoDB", dashboard_path %></h1>
    <ul class="right">      
      <li><%= link_to 'tables', "/dashboard/tables", :class => :tables %></a></li>
      <li><%= link_to 'visualizations', "/dashboard/visualizations", :class => :visualizations %></a></li>
      <li><%= link_to 'common data', dashboard_common_data_path, :class => selected_if(current_path == dashboard_common_data_path) %></a></li>
      <li><%= link_to 'documentation', Cartodb.config[:developers_host] %></a></li>
      <li>
        <a class="dropdown account separator" href="<%= account_url %>"><%= current_user.username %><span>|</span></a>
      </li>
    </ul>
  </div>
</header>

<%= yield :account_settings %>

app/views/admin/shared/_public_footer.html.erb
<footer>
  <div class="inner">
    <nav class="left">
      © <%= Date.today.year %> CartoDB <span>-</span> <%= link_to "Create your own maps", "http://cartodb.com/signup", { :class => "signup" } %>
    </nav>
    <p class="right"><%= link_to "Terms of Service", "http://cartodb.com/terms", :target => "blank" %></p>
  </div>
</footer>

app/views/admin/shared/_public_header.html.erb
<header>
  <div class="inner">
    <h1 class="left"><%= link_to "CartoDB", "http://www.cartodb.com" %></h1>
    <ul class="right">
    <li class="signin"><a href="http://cartodb.com/login" class="signin green button" title="Sign in">Sign in</a></li>
  </ul>
</div>
</header>

app/views/admin/shared/_public_vis_header.html.erb
<header class="vis">
  <div class="inner">

    <div class="header_content">
      <div class="left">
        <ul class="actions">
          <li><h1><%= link_to "CartoDB", "http://cartodb.com", :class => "logo" %></h1></li>
          <li><h2></h2></li>
          <li><span class="author"></span></li>
        </ul>
        <div class="description">
          <p class="public"></p>
        </div>
      </div>
      <div class="right">
        <ul class="options">
          <li><a class="button_header rounded white data_download"><span class="icon"></span>download this data</a></li>
          <li><%= link_to "sign in", login_path %></li>
        </ul>
      </div>
    </div>

    <div class="vis_navigation">
      <nav>
        <%= link_to "Table",    "#/table", :class => "smaller strong tab selected" %>
        <%= link_to "Map view", "#/map",   :class => "smaller strong tab" %>
      </nav>
    </div>

  </div>
</header>

app/views/admin/shared/_search.html.erb
<div class="inner">
  <div class="search search_bar">
    <a href="#" class="filter">Filter by tag</a>
  </div>
</div>

app/views/admin/shared/_subheader.html.erb
<div class="subheader <%= 'active' if @tables_count > 0 %>"></div>

app/views/admin/shared/_vis_header.html.erb
<header class="vis">
  <div class="inner">
    
    <div class="header_content">
      <div class="left">
        <ul class="actions">
          <li><%= link_to "Back", root_path, :class => "back" %></li>
          <li><span class="type">T</span></li>
          <li><h1><%= link_to "", "#/change-title", :class => "title" %></h1></li>
          <li><span class="tags"></span></li>
        </ul>
        <div class="description">
          <p><a href="#/change-description"></a></p>
        </div>
      </div>
      <div class="right">
        <ul class="options">
          <li><%= link_to "options", "#/options", :class => "dropdown options" %></li>
          <li>
            <a class="privacy rounded share" href="#/visualize"><i></i><span>VISUALIZE</span></a>
          </li>
        </ul>
      </div>
    </div>

    <div class="sync_status"></div>

    <div class="vis_navigation">
      <nav>
        <%= link_to "Table",    "#/table", :class => "smaller strong tab selected" %>
        <%= link_to "Map view", "#/map",   :class => "smaller strong tab" %>
      </nav>
      <div class="globalerror"></div>
    </div>

  </div>
</header>