config/routes.rb
# encoding: utf-8

CartoDB::Application.routes.draw do
  root :to => 'admin/pages#public'

  get   '/datasets' => 'admin/pages#datasets'

  get   '/login' => 'sessions#new', :as => :login
  get   '/logout' => 'sessions#destroy', :as => :logout
  match '/sessions/create' => 'sessions#create', :as => :create_session
  match '/limits' => 'home#limits', :as => :limits
  match '/status' => 'home#app_status'

  get   '/test' => 'test#index', :as => :test

  scope :module => 'admin' do
    get '/dashboard/'                         => 'visualizations#index', :as => :dashboard

    resource :organization, only: [:show] do
      resources :users, only: [:edit, :update, :create, :destroy, :new], constraints: { id: /[0-z\.\-]+/ }
    end

    # Tables
    get '/dashboard/tables'                         => 'visualizations#index'
    get '/dashboard/tables/:page'                   => 'visualizations#index'
    get '/dashboard/tables/tag/:tag'                => 'visualizations#index'
    get '/dashboard/tables/tag/:tag/:page'          => 'visualizations#index'

    # Visualizations
    get '/dashboard/visualizations'                 => 'visualizations#index'
    get '/dashboard/visualizations/:page'           => 'visualizations#index'
    get '/dashboard/visualizations/tag/:tag'        => 'visualizations#index'
    get '/dashboard/visualizations/tag/:tag/:page'  => 'visualizations#index'

    # Search
    get '/dashboard/search/:q'                      => 'visualizations#index'
    get '/dashboard/search/:q/:page'                => 'visualizations#index'

    get '/dashboard/visualizations/search/:q'                      => 'visualizations#index'
    get '/dashboard/visualizations/search/:q/:page'                => 'visualizations#index'

    get '/dashboard/tables/search/:q'                      => 'visualizations#index'
    get '/dashboard/tables/search/:q/:page'                => 'visualizations#index'

    # Tags
    get '/dashboard/tag/:tag'                       => 'visualizations#index'

    # Private dashboard
    get '/dashboard'                => 'visualizations#index'
    get '/dashboard/common_data'    => 'pages#common_data'

    # Public dashboard
    # root goes to 'pages#public'
    get '/page/:page'               => 'pages#public'
    get '/tag/:tag'                 => 'pages#public', :as => :public_tag
    get '/tag/:tag/:page'           => 'pages#public'

    get '/datasets/page/:page'      => 'pages#datasets'
    get '/datasets/tag/:tag'        => 'pages#datasets', :as => :dataset_public_tag
    get '/datasets/tag/:tag/:page'  => 'pages#datasets'

    get '/tables/track_embed'       => 'visualizations#track_embed'
    get '/tables/embed_forbidden'   => 'visualizations#embed_forbidden'
    get '/tables/embed_protected'   => 'visualizations#embed_protected'
    get '/tables/:id'               => 'visualizations#show'
    get '/tables/:id/map'           => 'visualizations#show'
    get '/tables/:id/table'         => 'visualizations#show'
    get '/tables/:id/public'        => 'visualizations#public'
    get '/tables/:id/public/table'  => 'visualizations#public'
    get '/tables/:id/public/map'    => 'visualizations#public'
    get '/tables/:id/embed_map'     => 'visualizations#embed_map'

    get '/viz'                      => 'visualizations#index'
    get '/viz/track_embed'          => 'visualizations#track_embed'
    get '/viz/embed_forbidden'      => 'visualizations#embed_forbidden'
    get '/viz/:id'                  => 'visualizations#show'
    get '/viz/:id/map'              => 'visualizations#show'
    get '/viz/:id/table'            => 'visualizations#show'
    get '/viz/:id/public'           => 'visualizations#public'
    get '/viz/:id/embed_map'        => 'visualizations#embed_map'
    get '/viz/:id/public_map'       => 'visualizations#public_map'

    get '/viz/:id/protected_embed_map'  => 'visualizations#show_protected_embed_map'
    post '/viz/:id/protected_embed_map' => 'visualizations#show_protected_embed_map', :as => :protected_embed_map

    get '/viz/:id/protected_public_map'  => 'visualizations#show_protected_public_map'
    post '/viz/:id/protected_public_map' => 'visualizations#show_protected_public_map', :as => :protected_public_map

    match '/your_apps' => 'client_applications#api_key', :as => :api_key_credentials
    post  '/your_apps/api_key/regenerate' => 'client_applications#regenerate_api_key', :as => :regenerate_api_key
    delete  '/your_apps/oauth'   => 'client_applications#oauth',   :as => :oauth_credentials

  end


  namespace :superadmin do
    resources :users
    resources :synchronizations
  end

  scope :oauth, :path => :oauth do
    match '/authorize'      => 'oauth#authorize',     :as => :authorize
    match '/request_token'  => 'oauth#request_token', :as => :request_token
    match '/access_token'   => 'oauth#access_token',  :as => :access_token
    get   '/identity'       => 'sessions#show'
  end

  scope '/api' do
    namespace CartoDB::API::VERSION_1, :format => :json, :module => 'api/json' do
      get    '/column_types'                                    => 'meta#column_types'

      get '/get_authenticated_users'                         => 'users#get_authenticated_users'

      resources :tables, :only => [:create, :show, :update] do
        collection do
          get '/tags/:tag_name' => 'tables#index', :as => 'show_tag'
        end

        resources :records, :only => [:index, :create, :show, :update, :destroy]
        resources :columns, :only => [:index, :create, :show, :update, :destroy]
      end

      # imports
      resources :uploads, :only                           => :create
      resources :imports, :only                           => [:create, :show, :index]
      get     '/imports/service/:id/token_valid'          => 'imports#service_token_valid?'
      get     '/imports/service/:id/list_files'           => 'imports#list_files_for_service'
      get     '/imports/service/:id/auth_url'             => 'imports#get_service_auth_url'
      get     '/imports/service/:id/validate_code/:code'  => 'imports#validate_service_oauth_code'
      delete  '/imports/service/:id/invalidate_token'     => 'imports#invalidate_service_token'
      # Must be GET verb
      get     '/imports/service/:id/oauth_callback/'  => 'imports#service_oauth_callback'

      # Dashboard
      resources :users, :only                       => [:show] do
        resources :layers, :only                    => [:create, :index, :update, :destroy]
        resources :assets, :only                    => [:create, :index, :destroy]
      end

      # Maps
      resources :maps, :only                        => [:show, :create, :update, :destroy] do
        resources :layers, :only                    => [:show, :index, :create, :update, :destroy]
      end

      # Geocoder
      resources :geocodings, :only                  => [:create, :show, :index, :update] do
        get 'country_data_for/:country_code', to: 'geocodings#country_data_for', on: :collection, as: 'country_data'
        get 'estimation_for/:table_name',     to: 'geocodings#estimation_for',   on: :collection, as: 'estimation_for'
        get 'get_countries',                  to: 'geocodings#get_countries',    on: :collection, as: 'get_countries'
      end

      get     'viz/tags' => 'tags#index', :as => 'list_tags'
      get     'viz'                                 => 'visualizations#index'
      post    'viz'                                 => 'visualizations#create'
      get     'viz/:id/stats'                       => 'visualizations#stats'
      get     'viz/:id'                             => 'visualizations#show'
      put     'viz/:id'                             => 'visualizations#update'
      delete  'viz/:id'                             => 'visualizations#destroy'
      get     'viz/:id/viz'                         => 'visualizations#vizjson1', as: :vizjson
      get     'viz/:visualization_id/overlays'      => 'overlays#index'
      post    'viz/:visualization_id/overlays'      => 'overlays#create'
      get     'viz/:visualization_id/overlays/:id'  => 'overlays#show'
      put     'viz/:visualization_id/overlays/:id'  => 'overlays#update'
      delete  'viz/:visualization_id/overlays/:id'  => 'overlays#destroy'

      # Tags
      resources :tags, :only                                    => [:index]
      # Synchronizations
      get     'synchronizations'              => 'synchronizations#index'
      post    'synchronizations'              => 'synchronizations#create'
      get     'synchronizations/:id'          => 'synchronizations#show'
      put     'synchronizations/:id'          => 'synchronizations#update'
      delete  'synchronizations/:id'          => 'synchronizations#destroy'
      get     'synchronizations/:id/sync_now' => 'synchronizations#syncing?'
      put     'synchronizations/:id/sync_now' => 'synchronizations#sync_now'
    end

    get '/v2/viz/:id/viz'    => 'api/json/visualizations#vizjson2', as: :vizjson
    get '/v2/wms'            => 'api/json/wms#proxy'
    
  end
end

app/models/visualization/copier.rb
# encoding: utf-8
require 'ostruct'
require_relative './name_generator'
require_relative '../map/copier'

module CartoDB
  module Visualization
    class Copier
      def initialize(user, visualization, name=nil)
        @user           = user
        @visualization  = visualization
        @name           = name
      end #initialize

      def copy
        Member.new(
          name:         new_name,
          tags:         visualization.tags,
          description:  visualization.description,
          type:         'derived',
          map_id:       map_copy.id,
          privacy:      visualization.privacy
        )
      end #copy

      private

      attr_reader :visualization, :user, :name

      def map_copy
        @map_copy ||= Map::Copier.new.copy(visualization.map)
      end #map

      def new_name
        @new_name ||= NameGenerator.new(user).name(name || visualization.name)
      end #name
    end # Copier
  end # Visualization
end # CartoDB

app/controllers/admin/visualizations_controller.rb
# encoding: utf-8
require_relative '../../models/map/presenter'
require_relative '../../models/visualization/locator'

class Admin::VisualizationsController < ApplicationController
  ssl_allowed :embed_map, :public_map, :show_protected_embed_map
  ssl_required :index, :show, :protected_embed_map, :protected_public_map, :show_protected_public_map
  before_filter :login_required, only: [:index]
  skip_before_filter :browser_is_html5_compliant?, only: [:public_map, :embed_map, :track_embed, :show_protected_embed_map, :show_protected_public_map]
  skip_before_filter :verify_authenticity_token, only: [:show_protected_public_map, :show_protected_embed_map]

  def index
    @tables_count  = current_user.tables.count
    @first_time    = !current_user.dashboard_viewed?
    @just_logged_in = !!flash['logged']
    current_user.view_dashboard
    update_user_last_activity
  end #index

  def show
    id = params.fetch(:id)
    return(redirect_to public_url_for(id)) unless current_user.present?
    @visualization, @table = locator.get(id, CartoDB.extract_subdomain(request))
    return(pretty_404) unless @visualization
    respond_to { |format| format.html }

    update_user_last_activity
  end #show

  def public
    id = params.fetch(:id)
    @visualization, @table = locator.get(id, CartoDB.extract_subdomain(request))

    return(pretty_404) if @visualization.nil? || @visualization.private?
    return(redirect_to public_map_url_for(id)) if @visualization.derived?

    @vizjson = @visualization.to_vizjson

    respond_to do |format|
      format.html { render 'public', layout: 'application_public' }
    end

  end #public

  def public_map
    id = params.fetch(:id)
    @visualization, @table = locator.get(id, CartoDB.extract_subdomain(request))
    
    return(pretty_404) unless @visualization
    return(embed_forbidden) if @visualization.private?
    return(public_map_protected) if @visualization.password_protected?

    response.headers['X-Cache-Channel'] = "#{@visualization.varnish_key}:vizjson"
    response.headers['Cache-Control']   = "no-cache,max-age=86400,must-revalidate, public"

    @avatar_url             = @visualization.user.gravatar(64)
    @disqus_shortname       = @visualization.user.disqus_shortname.presence || 'cartodb'
    @visualization_count    = @visualization.user.public_visualization_count
    @related_tables         = @visualization.related_tables
    @public_tables_count    = @visualization.user.table_count(::Table::PRIVACY_PUBLIC)
    @nonpublic_tables_count = @related_tables.select{|p| p.privacy != ::Table::PRIVACY_PUBLIC }.count

    respond_to do |format|
      format.html { render layout: false }
      format.js { render 'public_map', content_type: 'application/javascript' }
    end
  rescue
    embed_forbidden
  end #embed_map

  def show_protected_public_map
    id = params.fetch(:id)
    submitted_password = params.fetch(:password)
    @visualization, @table = locator.get(id, CartoDB.extract_subdomain(request))

    return(pretty_404) unless @visualization and @visualization.password_protected? and @visualization.has_password?

    if not @visualization.is_password_valid?(submitted_password)
      flash[:placeholder] = '*' * submitted_password.size()
      flash[:error] = "Invalid password"
      return(embed_protected)
    end

    response.headers['X-Cache-Channel'] = "#{@visualization.varnish_key}:vizjson"
    response.headers['Cache-Control']   = "no-cache,max-age=86400,must-revalidate, public"

    @protected_map_token = @visualization.get_auth_token()

    @avatar_url = @visualization.user.gravatar(64)

    @disqus_shortname       = @visualization.user.disqus_shortname.presence || 'cartodb'
    @visualization_count    = @visualization.user.public_visualization_count
    @related_tables         = @visualization.related_tables
    @public_tables_count    = @visualization.user.table_count(::Table::PRIVACY_PUBLIC)
    @nonpublic_tables_count = @related_tables.select{|p| p.privacy != ::Table::PRIVACY_PUBLIC }.count

    respond_to do |format|
      format.html { render 'public_map', layout: false }
    end    
  rescue
    public_map_protected
  end #show_protected_public_map

  def show_protected_embed_map
    id = params.fetch(:id)
    submitted_password = params.fetch(:password)
    @visualization, @table = locator.get(id, CartoDB.extract_subdomain(request))

    return(pretty_404) unless @visualization and @visualization.password_protected? and @visualization.has_password?

    if not @visualization.is_password_valid?(submitted_password)
      flash[:placeholder] = '*' * submitted_password.size()
      flash[:error] = "Invalid password"
      return(embed_protected)
    end

    response.headers['X-Cache-Channel'] = "#{@visualization.varnish_key}:vizjson"
    response.headers['Cache-Control']   = "no-cache,max-age=86400,must-revalidate, public"

    @protected_map_token = @visualization.get_auth_token()

    respond_to do |format|
      format.html { render 'embed_map', layout: false }
    end    
  rescue
    embed_protected
  end #show_protected_embed_map

  def embed_map
    id = params.fetch(:id)
    @visualization, @table = locator.get(id, CartoDB.extract_subdomain(request))
    
    return(pretty_404) unless @visualization
    return(embed_forbidden) if @visualization.private?
    return(embed_protected) if @visualization.password_protected?

    response.headers['X-Cache-Channel'] = "#{@visualization.varnish_key}:vizjson"
    response.headers['Cache-Control']   = "no-cache,max-age=86400,must-revalidate, public"

    respond_to do |format|
      format.html { render layout: false }
      format.js { render 'embed_map', content_type: 'application/javascript' }
    end
  rescue
    embed_forbidden
  end #embed_map

  # Renders input password view
  def embed_protected
    render 'embed_map_password', :layout => false
  end #embed_protected

  def public_map_protected
    render 'public_map_password', :layout => false
  end #public_map_protected

  def embed_forbidden
    render 'embed_map_error', layout: false, status: :forbidden
  end #embed_forbidden

  def track_embed
    response.headers['X-Cache-Channel'] = "embeds_google_analytics"
    response.headers['Cache-Control']   = "no-cache,max-age=86400,must-revalidate, public"
    render 'track', layout: false
  end #track_embed

  private

  def public_url_for(id)
    "/#{resource_base}/#{id}/public"
  end #public_url_for

  def public_map_url_for(id)
    "/#{resource_base}/#{id}/public_map"
  end #public_url_for

  def embed_map_url_for(id)
    "/#{resource_base}/#{id}/embed_map"
  end #public_url_for

  def resource_base
    return 'viz'    if request.path_info =~ %r{/viz/}
    return 'tables' if request.path_info =~ %r{/tables/}
  end #resource_base

  def download_formats table, format
    format.sql  { send_data table.to_sql, data_for(table, 'zip', 'zip') }
    format.kml  { send_data table.to_kml, data_for(table, 'zip', 'kmz') }
    format.csv  { send_data table.to_csv, data_for(table, 'zip', 'zip') }
    format.shp  { send_data table.to_shp, data_for(table, 'octet-stream', 'zip') }
  end

  def data_for(table, type, extension)
    { 
      type:         "application/#{type}; charset=binary; header=present",
      disposition:  "attachment; filename=#{table.name}.#{extension}"
    }
  end

  def update_user_last_activity
    return false unless current_user.present?
    current_user.set_last_active_time
    current_user.set_last_ip_address request.remote_ip
  end

  def pretty_404
    render(file: "public/404", layout: false, status: 404)
  end #pretty_404

  def locator
    CartoDB::Visualization::Locator.new
  end #locator
end # VisualizationsController

app/views/admin/visualizations/embed_map.js.erb
(function() {

    var INCLUDE_GMAPS = <% if @visualization.map.provider == 'googlemaps' %> true <% else %> false <% end %>;
    var VIZJSON_URL = '<%= vizjson_url(@visualization.id) %>';
    var ACCOUNT_TYPE = "<%= @visualization.user.account_type.downcase %>";
    var IS_CUSTOM_INSTALL = <%= Cartodb.config[:cartodb_com_hosted].present? %>;

    var doc = document;
    var head = doc.getElementsByTagName('head')[0];

    var global_info = window.__cartodb_embed = window.__cartodb_embed || {};
    global_info.scripts_loaded = global_info.scripts_loaded || [];
    global_info.load_queue = global_info.load_queue || [];
    global_info.gmaps_queue = global_info.gmaps_queue || [];

    function contains(array, v) {
      for(var i = 0; i < array.length; ++i) {
        if(array[i] == v) return true;
      }
      return false;
    }

    function search_embed_script_url() {
      var i, len, src;
      var scripts = document.getElementsByTagName('script');
      for (i = 0, len = scripts.length; i < len; ++i) {
        src = scripts[i].src;
        if(src && src.indexOf('embed_map.js') != -1 && !contains(global_info.scripts_loaded, src)) {
          global_info.scripts_loaded.push(src);
          return src;
        }
      }
      return null;
    }

    function get_url_params(url, conversion) {
      conversion = conversion || {};
      if(!url) {
        return {};
      }
      var search = url.split('?');
      if(search.length < 2) {
        return {};
      }
      search = search[1];
      var tokens = search.split('&');
      var params = {};
      for(var i = 0; i < tokens.length; ++i) {
        var tk = tokens[i].split('=');
        var fn = conversion[tk[0]] || function(v) { return v };
        if(tk.length === 2) {
          params[tk[0]] = fn(decodeURIComponent(tk[1]));
        }
      }
      return params;
    }

    var url = search_embed_script_url();

    var string_fn = function(v) { return v; }
    var bool_fn   = function(v) { return v == 'true' }
    var logo_fn   = function(v) { return ( ACCOUNT_TYPE != "coronelli" || IS_CUSTOM_INSTALL) ? true : v == 'true' };
    var layer_fn  = function(v) {
      var rt = [];
      var layers = v.split("|");
      for(var i = 0; i < layers.length; ++i) {
        rt.push({ visible: parseInt(layers[i], 10) });
      }
      return rt;
    };

    var opt = get_url_params(url, {
      'search': bool_fn,
      'title': bool_fn,
      'description': bool_fn,
      'shareable': bool_fn,
      'fullscreen': bool_fn,
      'cartodb_logo': bool_fn,
      'scrollwheel': bool_fn,
      'layer_selector': bool_fn,
      'sublayer_options':  layer_fn,
      'debug': bool_fn,
      'version': string_fn,
      'legends': bool_fn
    });


    function load_script(url, done) {
      var script = doc.createElement('script');
      script.type = 'text/javascript';
      script.src = url;
      script.async = true;
      var loaded = false;

      script.onload = script.onreadystatechange = function () {
        if ((script['readyState'] && script['readyState'] !== 'complete' && script['readyState'] !== 'loaded') || loaded) {
          return false
        }
        loaded = true;
        done && done();
      }
      head.appendChild(script)
    }

    var height = opt.height || '400';
    if(height.indexOf('%') == -1)  {
      height += 'px';
    }

    opt.version = opt.version ? (opt.version + '/'): '';

    if(!global_info.css_included) {
      doc.write('<link rel="stylesheet" href="http://libs.cartocdn.com/cartodb.js/v3/' + opt.version + 'themes/css/cartodb.css" />');
      var ua = navigator.userAgent;
      if(ua.indexOf('MSIE 8') != -1 || ua.indexOf('MSIE 7') != -1) {
        doc.write('<link rel="stylesheet" href="http://libs.cartocdn.com/cartodb.js/v3/' + opt.version + 'themes/css/cartodb.ie.css" />');
      }
      global_info.css_included = true
    }

    <% if Rails.env.development? %>
      opt.no_cdn = true;
    <% end %>

    var map_id = "cartodb-map-" + new Date().getTime();
    doc.write('<div class="cartodb-embed-map" id="' + map_id + '" style="height: ' + height + '"></div>');

    var load_cartodb = function() {
      if(typeof(cartodb) == "undefined") {
        if(global_info.loading) {
            global_info.load_queue.push([map_id, opt.url || VIZJSON_URL, opt]);
        } else {
          load_script('http://libs.cartocdn.com/cartodb.js/v3/' + (opt.debug ? ( opt.version + 'cartodb.uncompressed.js'):'cartodb.js'), function() {
            cartodb.createVis(map_id, opt.url || VIZJSON_URL, opt);

            for(var g in global_info.load_queue) {
              var params = global_info.load_queue[g];
              cartodb.createVis.apply(cartodb, params);
            }
          })
        }
        global_info.loading = true;
       } else {
          cartodb.createVis(map_id, opt.url || VIZJSON_URL, opt);
       }
    }

    if(INCLUDE_GMAPS) {
      if(!global_info.loading_gmaps && typeof(google) != 'undefined' && typeof(google.maps) != 'undefined') {
        load_cartodb();
      } else {
        if(global_info.loading_gmaps) {
          global_info.gmaps_queue.push(load_cartodb);
          return;
        }
        global_info.loading_gmaps = true;
        load_script("https://www.google.com/jsapi", function() {
        google.load("maps", "3.8", {
          "callback" : function() {
            global_info.loading_gmaps = false;
            load_cartodb()
            for(var i in global_info.gmaps_queue) {
                global_info.gmaps_queue[i]();
            }
          },
          other_params: "sensor=false"});
        });
      }
    } else {
      load_cartodb();
    }

    var l = document.createElement("a");
    l.href = url
    if(l.protocol.indexOf('http') != -1) {
        doc.write('<iframe style="display: none" src="' + l.protocol + '//' + l.hostname + ':' + l.port + '/viz/track_embed"></iframe>');
    }

})();

app/views/admin/visualizations/embed_map_password.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <%= favicon_link_tag "/favicons/favicon.ico" %>
    <title>Embed protected | CartoDB</title>
    <%= stylesheet_link_tag 'embeds/password_protected.css' %>
    <!--[if gte IE 9]>
    <style type="text/css">
      .gradient { filter: none; }
    </style>
    <![endif]-->
  </head>
  <body class="protected">
    <div class="bkg"></div>
    <div class="block modal creation">
      <div class="head">
        <h3>This map is protected by password</h3>
      </div>

      <div class="content">
        <%= form_tag(protected_embed_map_url(:protocol => Rails.env.development? ? 'http' : 'https') + '?' + request.query_string, {:method=>'POST',:authenticity_token=>false}) do %>
          <input type="password" name="password" placeholder="Insert your password" <% if (flash[:placeholder]) %>value="<%= flash[:placeholder] %>"<% end %> />
          <span class="icon"></span>
          <% if (flash[:error]) %>
            <span class="icon error" original-title="The password is not ok"></span>
          <% end %>
        <% end %>
      </div>

      <div class="foot">Contact with the owner in case you want access to it.</div>

    </div>

    <% if !Rails.env.production? %>
      <%= javascript_include_tag 'cdb.js' %>

    <% else %>
      <% if request.protocol == 'https://' %>
        <script src="https://cartodb-libs.global.ssl.fastly.net/cartodb.js/v3/cartodb.js"></script>
      <% else %>
        <script src="http://libs.cartocdn.com/cartodb.js/v3/cartodb.js"></script>
      <% end %>

    <% end %>

    <% if (flash[:error]) %>

      <%= javascript_include_tag "tipsy.js" %>
      <script type="text/javascript">
        $(function() {
          $("span.icon.error").tipsy({ gravity: "s", fade: true });
        });
      </script>
    <% end %>

    <%= render partial: 'shared/analytics', locals: {
      ua:     Cartodb.config[:google_analytics]['embeds'],
      domain: Cartodb.config[:google_analytics]['domain']
    } %>
  </body>
</html>

app/views/admin/visualizations/public_map_password.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <link rel="shortcut icon" href="/favicons/favicon.ico" />
    <title>Embed protected | CartoDB</title>
    <%= stylesheet_link_tag 'embeds/password_protected.css' %>
    <!--[if gte IE 9]>
    <style type="text/css">
      .gradient { filter: none; }
    </style>
    <![endif]-->
  </head>
  <body class="protected">
    <div class="bkg"></div>
    <div class="block modal creation">
      <div class="head">
        <h3>This map is protected by password</h3>
      </div>

      <div class="content">
        <%= form_tag(protected_public_map_url(:protocol => Rails.env.development? ? 'http' : 'https') + '?' + request.query_string, {:method=>'POST',:authenticity_token=>false}) do %>
          <input type="password" name="password" placeholder="Insert your password" <% if (flash[:placeholder]) %>value="<%= flash[:placeholder] %>"<% end %> />
          <span class="icon"></span>
          <% if (flash[:error]) %>
            <span class="icon error" original-title="The password is not ok"></span>
          <% end %>
        <% end %>
      </div>

      <div class="foot">Contact with the owner in case you want access to it.</div>

    </div>

    <% if !Rails.env.production? %>
      <%= javascript_include_tag 'cdb.js' %>

    <% else %>
      <% if request.protocol == 'https://' %>
        <script src="https://cartodb-libs.global.ssl.fastly.net/cartodb.js/v3/cartodb.js"></script>
      <% else %>
        <script src="http://libs.cartocdn.com/cartodb.js/v3/cartodb.js"></script>
      <% end %>

    <% end %>

    <% if (flash[:error]) %>

      <%= javascript_include_tag "tipsy.js" %>
      <script type="text/javascript">
        $(function() {
          $("span.icon.error").tipsy({ gravity: "s", fade: true });
        });
      </script>
    <% end %>

    <%= render partial: 'shared/analytics', locals: { 
      ua:     Cartodb.config[:google_analytics]['primary'],
      domain: Cartodb.config[:google_analytics]['domain']
    } %>
  </body>
</html>

app/views/admin/visualizations/track.html.erb
<!DOCTYPE html>
<html lang="en">
  <body>
    <%= render partial: 'shared/analytics', locals: { 
      ua:     Cartodb.config[:google_analytics]['embeds'],
      domain: Cartodb.config[:google_analytics]['domain'],
      page_owner: ''
    } %>
  </body>
</html>